name: action

on:
  schedule:
    - cron: "0 9-18 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-18.04
    steps:
      - uses: Caiyou1001/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
